const GET_FORECAST_STARTED = "GET_FORECAST_STARTED";
const GET_FORECAST_SUCCESS = "GET_FORECAST_SUCCESS";
const GET_FORECAST_FAILURE = "GET_FORECAST_FAILURE";

export {
  GET_FORECAST_STARTED,
  GET_FORECAST_SUCCESS,
  GET_FORECAST_FAILURE
};
